# Ordered Sets, hw4, Burtsev Anatolii

In [123]:
# You are given the following training set:
# 2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8,+
# 6,11,6,8,5,6,11,5,6,11,9,4,3,12,2,4,+
# 1,0,2,1,0,7,14,1,4,7,10,8,0,8,0,8,+
# 2,7,4,4,1,8,15,1,5,6,11,8,0,8,0,8,+
# 6,9,8,8,8,8,7,3,5,7,8,8,6,8,4,5,-
# 5,10,7,8,5,8,3,3,1,7,1,8,5,9,5,8,-
# 3,7,5,5,3,11,3,2,2,8,2,9,3,4,2,8,-

# and the following test set:
# 3,9,5,7,3,12,3,4,3,11,1,9,2,6,3,9
# 3,8,5,5,1,6,6,3,1,6,0,8,2,6,1,7
# 3,2,4,3,2,8,7,3,9,6,6,8,2,8,6,8

# a) Please find all “weak” hypothesis, or in other words, hypothesis which allow one counterexample.
# b) Find target classes for test set, using “weak” hypothesis from a)

In [124]:
import numpy as np

In [125]:
g1 = [2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8]
g2 = [6,11,6,8,5,6,11,5,6,11,9,4,3,12,2,4]
g3 = [1,0,2,1,0,7,14,1,4,7,10,8,0,8,0,8]
g4 = [2,7,4,4,1,8,15,1,5,6,11,8,0,8,0,8]

In [126]:
g_plus = np.array([g1, g2, g3, g4])

In [127]:
g5 = [6,9,8,8,8,8,7,3,5,7,8,8,6,8,4,5]
g6 = [5,10,7,8,5,8,3,3,1,7,1,8,5,9,5,8]
g7 = [3,7,5,5,3,11,3,2,2,8,2,9,3,4,2,8]

In [128]:
g_minus = np.array([g5, g6, g7])

In [129]:
g8 = [3,9,5,7,3,12,3,4,3,11,1,9,2,6,3,9]
g9 = [3,8,5,5,1,6,6,3,1,6,0,8,2,6,1,7]
g10= [3,2,4,3,2,8,7,3,9,6,6,8,2,8,6,8]

In [130]:
g_test = np.array([g8, g9, g10])

In [131]:
g_minus_low = g_minus.min(axis=0)
g_minus_high = g_minus.max(axis=0)
g_plus_low = g_plus.min(axis=0)
g_plus_high = g_plus.max(axis=0)

# let's check is any of test's instance included in Class + or Class -

In [132]:
(g_test >= g_plus_low).min(axis=1), (g_test <= g_plus_high).min(axis=1)

(array([False, False, False]), array([False,  True, False]))

In [133]:
(g_test >= g_minus_low).min(axis=1), (g_test <= g_minus_high).min(axis=1)

(array([False, False, False]), array([False,  True, False]))

# not anyone test's instance doesn't satisfy common hypothesis for both classes. 
# Let's check weak hypothesis

In [134]:
def build_weak_hypothesis(first_class, second_class, i):
    # build weak hypothesis for all first_class and one instance from second class with index i
    g = np.concatenate((first_class, second_class[i].reshape([1, -1])))
    low = g.min(axis=0)
    high = g.max(axis=0)
    c = 0
    for j in range(second_class.shape[0]):
        g_counter = second_class[j]
        if (g_counter >= low).all() and (g_counter <= high).all():
            c += 1
    # allow only one counter example
    if c <= 1:
        return np.array((low, high))


# first weak hypothesis for class + and first element from class -

In [135]:
hp1 = build_weak_hypothesis(g_plus, g_minus, 0)

In [136]:
hp1

array([[ 1,  0,  2,  1,  0,  6,  7,  0,  4,  6,  8,  4,  0,  8,  0,  4],
       [ 6, 11,  8,  8,  8,  8, 15,  5,  6, 11, 11,  8,  6, 12,  4,  8]])

# compare it with just class + (they differs, weak hypothesis wider)

In [137]:
g_plus_low, g_plus_high

(array([ 1,  0,  2,  1,  0,  6, 11,  0,  4,  6,  9,  4,  0,  8,  0,  4]),
 array([ 6, 11,  6,  8,  5,  8, 15,  5,  6, 11, 11,  8,  3, 12,  2,  8]))

In [138]:
hp2 = build_weak_hypothesis(g_plus, g_minus, 1)

In [139]:
hp3 = build_weak_hypothesis(g_plus, g_minus, 2)

In [140]:
hm1 = build_weak_hypothesis(g_minus, g_plus, 0)

In [141]:
hm2 = build_weak_hypothesis(g_minus, g_plus, 1)

In [142]:
hm3 = build_weak_hypothesis(g_minus, g_plus, 2)

In [143]:
hm4 = build_weak_hypothesis(g_minus, g_plus, 3)

# all weak hypothesis (lower and upper bounds for each)

In [144]:
hp1

array([[ 1,  0,  2,  1,  0,  6,  7,  0,  4,  6,  8,  4,  0,  8,  0,  4],
       [ 6, 11,  8,  8,  8,  8, 15,  5,  6, 11, 11,  8,  6, 12,  4,  8]])

In [145]:
hp2

array([[ 1,  0,  2,  1,  0,  6,  3,  0,  1,  6,  1,  4,  0,  8,  0,  4],
       [ 6, 11,  7,  8,  5,  8, 15,  5,  6, 11, 11,  8,  5, 12,  5,  8]])

In [146]:
hp3

array([[ 1,  0,  2,  1,  0,  6,  3,  0,  2,  6,  2,  4,  0,  4,  0,  4],
       [ 6, 11,  6,  8,  5, 11, 15,  5,  6, 11, 11,  9,  3, 12,  2,  8]])

In [147]:
hm1

array([[ 2,  7,  3,  5,  1,  8,  3,  0,  1,  6,  1,  8,  0,  4,  0,  5],
       [ 6, 10,  8,  8,  8, 11, 13,  3,  6,  8, 10,  9,  6,  9,  5,  8]])

In [148]:
hm2

array([[ 3,  7,  5,  5,  3,  6,  3,  2,  1,  7,  1,  4,  3,  4,  2,  4],
       [ 6, 11,  8,  8,  8, 11, 11,  5,  6, 11,  9,  9,  6, 12,  5,  8]])

In [149]:
hm3

array([[ 1,  0,  2,  1,  0,  7,  3,  1,  1,  7,  1,  8,  0,  4,  0,  5],
       [ 6, 10,  8,  8,  8, 11, 14,  3,  5,  8, 10,  9,  6,  9,  5,  8]])

In [150]:
hm4

array([[ 2,  7,  4,  4,  1,  8,  3,  1,  1,  6,  1,  8,  0,  4,  0,  5],
       [ 6, 10,  8,  8,  8, 11, 15,  3,  5,  8, 11,  9,  6,  9,  5,  8]])

In [151]:
def is_it_satisfy_hypothesis(hypot, gt):
    return (hypot[0] <= gt).all() and (hypot[1] >= gt).all()

# time to check is one of test's instances satisfy any of weak hypothesis

In [152]:
for h in [hp1, hp2, hp3, hm1, hm2, hm3, hm4]:
    print(is_it_satisfy_hypothesis(h, g8))

False
False
False
False
False
False
False


In [153]:
for h in [hp1, hp2, hp3, hm1, hm2, hm3, hm4]:
    print(is_it_satisfy_hypothesis(h, g9))

False
False
False
False
False
False
False


In [154]:
for h in [hp1, hp2, hp3, hm1, hm2, hm3, hm4]:
    print(is_it_satisfy_hypothesis(h, g10))

False
False
False
False
False
False
False


No one of our weak hypothesis could classify test's instances 

# № 3

Follow the algorithm of lazy classification – intersect test object description with descriptions from training set one by one.
Define a classification rule such that, test objects 1) and 3) will be classified as class 1, and object 2) as class 2

In [155]:
train = np.concatenate((g_plus, g_minus))
train.shape

(7, 16)

classification rules look like that:

min votes = 0

min votes difference = 2


if amount of voice for class 2 is even -> class 2, else -> class 1

You could see work of this classifier at the end of page

In [156]:
def classifier(g_test):
    pre_votes = voting(g_test, min_votes=0, min_votes_diff=2)
    votes = votes_to_decision(pre_votes)
    if votes[1] % 2 == 1:
        return 2
    else: 
        return 1

In [157]:
def voting(g_test, min_votes=2, min_votes_diff=2):
    votes = []
    for i in range(train.shape[0]):
        g = np.concatenate((g_test, train[i]))
        low = g.min(axis=0)
        high = g.max(axis=0)
        pre_votes_plus = 0
        pre_votes_minus = 0
        for j in range(g_plus.shape[0]):
            gp = g_plus[j]
            if (gp >= low).all() and (gp <= high).all():
                pre_votes_plus += 1
        for j in range(g_minus.shape[0]):
            gm = g_minus[j]
            if (gm >= low).all() and (gm <= high).all():
                pre_votes_minus += 1
        if pre_votes_plus < min_votes and pre_votes_minus < min_votes:
            continue
        if pre_votes_plus == pre_votes_minus:
            continue
        if abs(pre_votes_plus - pre_votes_minus) < min_votes_diff:
            continue
        votes.append((pre_votes_plus, pre_votes_minus))
        
    return np.array(votes)

In [158]:
def votes_to_decision(votes):
    votes_for_plus = 1*(votes[:,0] > votes[:, 1]).sum()
    votes_for_minus = 1*(votes[:,0] < votes[:, 1]).sum()
    return (votes_for_plus, votes_for_minus)

In [159]:
classifier(g8)

1

In [160]:
classifier(g9)

2

In [161]:
classifier(g10)

1